# Generated by Django 4.1.1 on 2022-12-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Order_id', models.CharField(max_length=65, verbose_name='customer_Order_id')),
                ('customer_id', models.CharField(max_length=65, verbose_name='customer_id')),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(max_length=65, verbose_name='payment_mode')),
            ],
        ),
    ]
