# Generated by Django 4.1.1 on 2022-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=65, verbose_name='customer_id')),
                ('first_name', models.CharField(max_length=65, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=65, verbose_name='last_name')),
                ('gender', models.CharField(max_length=65, verbose_name='gender')),
                ('phone_number', models.IntegerField(max_length=65, verbose_name='phone_number')),
                ('email', models.CharField(max_length=65, verbose_name='email')),
                ('roll', models.CharField(default='customer', max_length=65, verbose_name='roll')),
                ('password', models.CharField(max_length=65, verbose_name=' password')),
                ('location', models.CharField(max_length=500, verbose_name=' location')),
            ],
        ),
        migrations.CreateModel(
            name='DealerSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.CharField(max_length=65, verbose_name='first_name')),
                ('first_name', models.CharField(max_length=65, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=65, verbose_name='last_name')),
                ('gender', models.CharField(max_length=65, verbose_name='gender')),
                ('gst', models.IntegerField(max_length=65, verbose_name='gender')),
                ('dealer_type', models.CharField(max_length=65, verbose_name='dealer_type')),
                ('email', models.CharField(max_length=65, verbose_name='email')),
                ('roll', models.CharField(default='dealer', max_length=65, verbose_name='roll')),
                ('password', models.CharField(max_length=65, verbose_name=' password')),
                ('location', models.CharField(max_length=65, verbose_name=' location')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=65, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=65, verbose_name='last_name')),
                ('gender', models.CharField(max_length=65, verbose_name='gender')),
                ('email', models.CharField(max_length=65, verbose_name='email')),
                ('roll', models.CharField(default='EMP', max_length=65, verbose_name='roll')),
                ('password', models.CharField(max_length=65, verbose_name=' password')),
            ],
        ),
    ]
