# Generated by Django 4.1.1 on 2022-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0002_alter_customersignup_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealersignup',
            name='gst',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
