# Generated by Django 4.1.1 on 2022-12-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0003_alter_dealersignup_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersignup',
            name='phone_number',
            field=models.CharField(max_length=10, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='dealersignup',
            name='gst',
            field=models.IntegerField(max_length=65, verbose_name='gst'),
        ),
    ]
